name: e_commerce
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3
dependencies:
  anim_search_bar: ^2.0.3
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  data_connection_checker_tv: ^0.3.5-nullsafety
  dio: ^5.7.0
  dynamic_color: ^1.7.0
  equatable: ^2.0.7
  firebase_analytics: ^11.3.6
  firebase_core: ^3.8.1
  firebase_messaging: ^15.1.6
  flex_color_scheme: ^8.0.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^9.2.2
  get_it: ^8.0.2
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  intl: ^0.19.0
  pinput: ^5.0.0
  rive: ^0.13.20
  shared_preferences: ^2.3.3
  shimmer: ^3.0.0
  svg_flutter: ^0.0.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/illustrations/
    - assets/rive/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
